import Head from "next/head";
import { Inter } from "@next/font/google";
import { Header } from "../components/main/Header";
import { Body } from "../components/main/Body";

const inter = Inter({ subsets: ["latin"] });

export function Home() {
  return (
    <>
      <Head>
        <title>Login</title>
        <meta name="description" content="Generated by no one ;)" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={inter.className}>
        <Header />
        <Body />
      </main>
    </>
  );
}
