import Head from "next/head";
import { Auth, ThemeSupa } from "@supabase/auth-ui-react";
import { useSession, useSupabaseClient } from "@supabase/auth-helpers-react";
import { Inter } from "@next/font/google";
import Header from "../components/main/Header";
import Body from "../components/main/Body";
import Account from "../components/main/Account";

const inter = Inter({ subsets: ["latin"] });

const Home = () => {
  const session = useSession();
  const supabase = useSupabaseClient();
  return (
    <>
      <Head>
        <title>${session ? "Welcome NAME_HERE" : "Login"}Login</title>
        <meta name="description" content="Generated by no one ;)" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {!session ? (
        <Auth supabaseClient={supabase} appearance={{ theme: ThemeSupa }} theme="dark" />
      ) : (
        <Account session={session} />
      )}
      <main className={inter.className}>
        <Header />
        <Body />
      </main>
    </>
  );
};
export default Home;
